version: "3.8"
name: e3s
services:
  db:
    image: postgres:13
    container_name: postgres
    volumes:
      - "pgdata-volume:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s  
    networks:
      - data-network
  e3s-migration:
    image: public.ecr.aws/zebrunner/e3s-migration:1.0
    container_name: e3s-migration
    environment:
      DATABASE: postgres://postgres:postgres@db/postgres?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    networks:
      - data-network
  redis:
    image: redis:6.2.6
    container_name: redis
    restart: always
    networks:
      - data-network
volumes:
  pgdata-volume:
networks:
  data-network:
    external: true
    name: e3s-network
