{
 "title": "E3S",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "E3S instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available storage percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "e3s_instance:storage:availiable_percent"
      }
     ]
    },
    {
     "title": "RAM usage percent",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
     "targets": [
      { "expr": "e3s_instance:ram:usage_percent" }
     ]
    },
    {
     "title": "CPU usage percent",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "e3s_instance:cpu:usage_percent_2m_rate"
      }
     ]
    },
    {
     "title": "Network Traffic In (MB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "e3s_instance:network:throughput_in_mb_s_rate_2m"
      }
     ]
    },
    {
     "title": "Network Traffic Out (MB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "e3s_instance:network:throughput_out_mb_s_rate_2m"
      }
     ]
    }
   ]
  },
  {
   "title": "Linux Agent Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "RAM usage percent",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "linux_instances:ram:usage_percent"
      }
     ]
    },
    {
     "title": "CPU usage percent",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "linux_instances:cpu:usage_percent_2m_rate"
      }
     ]
    },
    {
     "title": "Network Traffic In (MB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "linux_instances:network:throughput_mb_s_rate_2m"
      }
     ]
    },
    {
     "title": "Network Traffic Out (MB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "linux_instances:network:throughput_out_mb_s_rate_2m"
      }
     ]
    },
    {
     "title": "Container RAM in use percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "linux_instances:container_ram:in_use_percent",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Container RAM in use percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "linux_instances:container_cpu:in_use_percent",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Windows Agent Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "RAM usage percent",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "windows_instances:ram:usage_percent"
      }
     ]
    },
    {
     "title": "CPU usage percent",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "windows_instances:cpu:usage_percent_2m_rate"
      }
     ]
    },
    {
     "title": "Network Traffic In (MB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "windows_instances:network:throughput_in_mb_s_rate_2m"
      }
     ]
    },
    {
     "title": "Network Traffic Out (MB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "targets": [
      {
       "expr": "windows_instances:network:throughput_out_mb_s_rate_2m"
      }
     ]
    },
    {
     "title": "Container RAM in use percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "windows_instances:container_ram:in_use_mb",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Container CPU in use percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "targets": [
      {
       "expr": "windows_instances:container_cpu:in_use_percent"
      }
     ]
    }
   ]
  }
 ]
}