global:
  scrape_interval: 5s
rule_files:
  - rules.yml
  - alerts.yml
alerting:
  alertmanagers:
   - static_configs:
     - targets:
        - alert-manager:9093
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: e3s_instance
    static_configs:
      - targets:
        - node-exporter:9100
  # - job_name: router_1
  #   static_configs:
  #     - targets:
  #       - 127.0.0.1:4444
  - job_name: 'ec2_node_exporter_discovery'
    ec2_sd_configs:
      - port: 9100 # referred to nodeExporter exposed port
        #role_arn: arn:aws:iam::342241566140:role/Ec2-Instance-Role
        filters:
        - name: tag:aws:autoscaling:groupName
          values:
          - e3s-{env}-linux-asg
            e3s-{env}-windows-asg
  - job_name: ecs_CAdvisor
    ec2_sd_configs:
      - port: 8080 # referred to cAdvisor exposed port
        #role_arn: arn:aws:iam::342241566140:role/Ec2-Instance-Role
        filters:
        - name: tag:aws:autoscaling:groupName
          values:
          - e3s-{env}-linux-asg
            e3s-{env}-windows-asg
