global:
  scrape_interval: 15s
rule_files:
  - rules.yml
  - alerts.yml
alerting:
  alertmanagers:
   - static_configs:
     - targets:
        - 127.0.0.1:9093

scrape_configs:
  - job_name: e3s_instance
    static_configs:
      - targets:
        - 127.0.0.1:9100

  - job_name: 'ecs_linux_node'
    ec2_sd_configs:
      - region: {region}
        port: 9100
        filters:
        - name: tag:aws:autoscaling:groupName
          values:
          - e3s-{env}-linux-asg
  - job_name: ecs_linux_cAdvisor
    ec2_sd_configs:
      - region: {region}
        port: 8080
        filters:
        - name: tag:aws:autoscaling:groupName
          values:
          - e3s-{env}-linux-asg

  - job_name: ecs_windows_exporter
    ec2_sd_configs:
      - region: {region}
        port: 9182
        filters:
        - name: tag:aws:autoscaling:groupName
          values:
          - e3s-{env}-windows-asg
