groups:

  - name: cpu_computation
    rules:
    - record: job:idle_cpu_seconds:avg_per_minute
      expr: avg without(cpu)(rate(node_cpu_seconds_total{mode='idle'}[1m]))

    - record: job:non_idle_cpu_seconds:avg_per_minute
      expr: avg without(cpu, mode)(rate(node_cpu_seconds_total{mode!='idle'}[1m]))
        
  - name: memory_computation
    rules:
    - record: job:free_memory:percentage
      expr: (node_memory_MemFree_bytes/node_memory_MemTotal_bytes)*100

    - record: job:busy_memory:percentage
      expr: (1-(node_memory_MemFree_bytes/node_memory_MemTotal_bytes))*100

    - record: job:node_memory_Mem_bytes:available
      expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100

  - name: requests
    rules:
    - record: job:go_app_response_latency:rate_1m
      expr: rate(go_app_response_latency_seconds_sum{path="/user/{name}"}[1m]) /rate(go_app_response_latency_seconds_count{path="/user/{name}"}[1m])
