apiVersion: 1

prune: true

datasources:
  - name: Prometheus
    type: prometheus
    url: http://{e3s_private_ip}:9090
    isDefault: true
    access: proxy
    editable: true

  - name: Alertmanager
    type: alertmanager
    url: http://{e3s_private_ip}:9093
    isDefault: false
    access: proxy
    editable: true
